apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
        - name: zabbix-frontend
          image: zabbix/zabbix-web-nginx-mysql:latest
          envFrom:
            - configMapRef:
                name: zabbix-config
          env:
            - name: DB_SERVER_HOST
              value: "zabbix-mysql"
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: MYSQL_USER
              value: "zabbix"
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zabbix-config
                  key: ZBX_SERVER_DB_PASSWORD
          ports:
            - containerPort: 80
