apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-mysql
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-mysql
  template:
    metadata:
      labels:
        app: zabbix-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: MYSQL_USER
              value: "zabbix"
            - name: MYSQL_PASSWORD
              value: "zabbix_db_password"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: zabbix-pvc
