apiVersion: v1
kind: Service
metadata:
  name: zabbix-mysql
  namespace: zabbix
spec:
  ports:
    - port: 3306
  selector:
    app: zabbix-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  ports:
    - port: 10051
  selector:
    app: zabbix-server
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
  namespace: zabbix
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: zabbix-frontend
